indent = 4
margin = 92
always_for_in = true
for_in_replacement = "in"
whitespace_typedefs = true
whitespace_ops_in_indices = true
remove_extra_newlines = true
import_to_using = true
pipe_to_function_call = true
short_to_long_function_def = false
force_long_function_def = false
long_to_short_function_def = false
always_use_return = false
whitespace_in_kwargs = true
annotate_untyped_fields_with_any = false
format_docstrings = false
conditional_to_if = false
normalize_line_endings = "unix"
trailing_comma = true
trailing_zero = true  # TODO
join_lines_based_on_source = false
indent_submodule = false
separate_kwargs_with_semicolon = false
surround_whereop_typeparameters = true
short_circuit_to_if = false
disallow_single_arg_nesting = true
verbose = true